### ISSUE TITLE
Checking for Updates is an INFO message

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge-device-agent#10]
### Current Behavior

The agent checks for an update every 30s and if there are no new snapshots it logs 2 lines:
```
[2022-06-15T06:39:14.529Z] INFO: Calling home
[2022-06-15T06:39:14.743Z] INFO: No updated needed
```

This produces a lot of log data if left running, 

### Expected Behavior

These messages should only be shown at the DEBUG level.
If there is an update found this should be an INFO message
if there is an error (4xx etc) this should be an ERROR message

### Steps To Reproduce

Run the agent, watch the log

### Environment

- FlowForge Agent version: 0.0.1
- Node.js version: 16
- npm version: 8
- Platform/OS: Raspbian
- Browser:

**Comment by ZJvandeWeg** [comment]
>>>
If there is an update found this should be an INFO message
if there is an error (4xx etc) this should be an ERROR message
>>>
This seems to be already the case.

**Comment by sammachin** [comment]
> > > >
> 
> If there is an update found this should be an INFO message if there is an error (4xx etc) this should be an ERROR message
> 
> > > >
> 
> This seems to be already the case.

Yes this was just confirming what the whole experience should be
