### ISSUE TITLE
Allow local configuration of https/httpStatic on a device

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge-device-agent#110]
### Description

When running instances inside the platform, the https configuration is handled by the platform and the user has no need to deal with it.

However, when running on a device a user may need https to be configured. This requires configuring certificates and other options in the settings.js file.

Similarly, the `httpStatic` setting is one that we have elected not to expose in the cloud platform (due to the difficulties in managing files within the instance image). However, on a device, where the user has full file system access, it is more reasonable to support httpStatic.

The proposal here is to allow both of these things to be configured locally on the device agent.

A user could provide a set of options via the `device.yml` file that the device agent applies to the generated settings.js file.

### Acceptance Criteria

- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3
- ...

**Comment by Steve-Mcl** [comment]
@knolleary having just raised these PRs (and are fresh in your mind) could you please update the OP of this issue with acceptance criteria?  Will help me in review. Ta.
