### ISSUE TITLE
Upgrade Node-RED version on device

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge-device-agent#12]
### Description

When my flows are tested and developed with a certain Node-RED version, or there's a security upgrade to a certain Node-RED version, I'd want to roll out these changes to all my devices. This means that the agent should install the new Node-RED version.

**Comment by knolleary** [comment]
When a snapshot is pushed to a device, it includes the information about the version of Node-RED in the project stack. The device agent will then npm install that version of node-red as part of deploying the project.

**Comment by sammachin** [comment]
However the snapshot listing does not currently show the version that a snapshot is built on so I've raised https://github.com/flowforge/flowforge/issues/703 to display this.

**Comment by sammachin** [comment]
No because the solution is implemented the way to update the version of Node-RED on a device is to create and deploy a new snapshot.  I've created the additional story in the comment to help users identify the version of Node-RED in their current snapshot

**Comment by sammachin** [comment]
Node-RED is a dependency in the project so its installed as part of that, here's the package.json from a snapshot:
```
pi@sensehatpi:/opt/flowforge-device/project $ cat package.json 
{
  "name": "flowforge-project",
  "description": "A FlowForge Project",
  "private": true,
  "version": "0.0.1",
  "dependencies": {
    "node-red": "2.2.2",
    "node-red-node-pi-sense-hat": "0.1.1"
  }
}
```
