### ISSUE TITLE
Add support for Node 14

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge-device-agent#123]
### Description

Currently the Device Agent requires node 16 or later. That was chosen due to it being the current LTS version at the time of writing and was the right choice.

Whilst Node 14 has reached its end of life, there are a number of devices stuck at that level and likely to be for some time.

We have had a specific request to support Node 14 on the device agent. I haven't sniff tested it yet, but I do not think it will be a large task to get it working. Mostly likely a bit of syntactic sugar will have to be gotten rid of and done the old-fashioned way.

**Comment by Steve-Mcl** [comment]
Happy to pick this up Nick
