### ISSUE TITLE
Remote device editor not working on local install

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge-device-agent#124]
### Current Behavior

Noticed while working on https://github.com/flowforge/flowforge/issues/2323 that I could not connect via tunnel:

![image](https://github.com/flowforge/flowforge-device-agent/assets/44235289/c517814f-cc89-41b1-ac57-297b658d52a7)

was working in previous release

### Expected Behavior

Tunnel should auto connect user to remote device's editor

### Steps To Reproduce

Running localfs, on windows, enable developer mode, turn on Editor Access, launch remote editor from the FF link.

### Environment

- FlowForge version: 1.8.x-github
- Agent version: 1.9.2-github
- Node.js version: 16
- Platform/OS: windows
- Browser: Chrome latest

**Comment by hardillb** [comment]
@Steve-Mcl we need the device agent logs (in verbose mode) to go with this

**Comment by Steve-Mcl** [comment]
ok, will get that shortly.

wish we could turn on logs via a remote command - would make this much easier.  

will raise a issue/feature request on that too.

**Comment by Steve-Mcl** [comment]
Pretty sure this was down to my system Ben. 

I will close it for now.
