### ISSUE TITLE
Device logs become unavailable if more than one browser views them

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge-device-agent#126]
### Current Behavior

Device Logs become inaccessible if more than one browser access them

![image](https://github.com/flowforge/flowforge-device-agent/assets/44235289/bea227bb-3ac0-4d74-8179-493ec5e36af2)

### Expected Behavior

multiple views should be possible

### Steps To Reproduce

STAGING:

1. Log onto staging
2. Locate a working device (or add one)
3. View the device's logs in browser 1 (e.g. chrome)
   * Logs Working
4. log into staging via a 2nd browser and access the logs of the same device
   * Logs NOT Working
5. refresh browser 1
   * Logs NOT Working
 
LOCAL: (localfs)
1. Log onto local FF 
2. Add a working device
3. View the device's logs in browser 1 (e.g. chrome)
   * Logs Working 
5. log into staging via a 2nd browser and access the logs of the same device
   * Logs NOT Working
6. refresh browser 1
   * Logs NOT Working
   
   
ATTEMPTS TO RECOVER LOGS:
Stop / start device - NOK
Log out both browsers, log back in 1 or other - NOK
Stop / start FF - NOK
Log out browsers + close browsers + stop agent, start agent, open one browser, login, view logs - NOK

### Environment

- FlowForge version: 1.8 (staging)
- Agent 1.9.2 (git main), V0.8.0
- Node.js version: 16
- npm version:
- Platform/OS: Windows
- Browser: Chrome + Edge (both up to date)

**Comment by Steve-Mcl** [comment]
Bug verified by @knolleary in local env.

**Comment by knolleary** [comment]
A secondary issue is that whilst the *first* websocket gets the backlog of logs, the *second* one only gets new logs... so it can appear not to be working if the device isn't actively logging anything.

Will need to do some log caching in the platform I think so we can provide a bit of history when subsequent websockets open

**Comment by knolleary** [comment]
A tertiary issue is the device can get into a state where its sending logs to the platform even if no-one is listening. The platform needs to tell the device to stop if that is the case.
