### ISSUE TITLE
NR not starting on device - ( Cannot GET / ) 

### ISSUE THREAD

**Issue by grawsom** [flowforge/flowforge-device-agent#14]
### Current Behavior

Don't know if I have missed something, but have now tried this a couple off times, also on Windows, but GH and FF web is out of sync - No where on webpage does it says `The agent does not support running on Windows.` as on this github page.
Just for info

Okay when I'm launching NR 127.0.0.1:1880, I get `Cannot GET / `

This is what I have on my device.

![Billede uden titel](https://user-images.githubusercontent.com/6400532/175813962-d5e3bd89-8a5e-4112-8cb4-24ab84a943d7.png)

### Expected Behavior

See NR editor

### Steps To Reproduce

I have FF running on windows, configured with host 0.0.0.0, url as http://192.168.1.100:3000, so my RPI can reach my FF PC 

### Environment

- FlowForge version:  0.6.2
- Node.js version: 16.13.2
- npm version: 8.10.0
- Platform/OS: Win11
- Browser: Chromium (Raspberry)
- Device

![device](https://user-images.githubusercontent.com/6400532/175814055-332b7579-1024-4473-b13a-3f8a5eaf92db.png)

**Comment by hardillb** [comment]
Windows is not supported for the Device Agent, will make sure the doc is updated on Monday

**Comment by hardillb** [comment]
You are not supposed to be able to get get to the editor on the device, this is working as intended.

You edit the flows on the cloud, not the device.

**Comment by grawsom** [comment]
Okay this makes sence then why I'm seeing what I'm seeing, I will play on with this GREAT feature - is just what I have been looking for in a loooong time - let's close this .
Thank's for fast feedback 👍
