### ISSUE TITLE
Question - localfilesystem, and local testing/see stuff via browser as normal NR installation

### ISSUE THREAD

**Issue by grawsom** [flowforge/flowforge-device-agent#15]
### Current Behavior

Is this the right way if you have a question?

At the moment I have this contextStorage enabled in settings.js

`contextStorage: {
         default: {
             module:"localfilesystem"
         },
     },`

How to get this configured/enabled with FF / device?

Had an issue the other day and got answeer from @hardillb that you can't use editor on device.
But how do I then test, see whats going on?
I have devices with serialport/GSM dongle, where you enable/disable flows for when you need to see info regading GSM signal etc. - problem here is that you can't have it working and also have info, so I need to stop something (is in UI) when using tools.  

### Expected Behavior

That you still can use NR as normal on the device

### Environment

- FlowForge version: 0.6.2
- Node.js version: 16.13.2
- npm version: 8.10.0
- Platform/OS: 
- Browser:

**Comment by hardillb** [comment]
Changing the `contextStorage` in FlowForge is not yet supported, at the moment everything uses the default in memory storage for the context.

For the cloud side we are looking at (in the future) adding support for a persistent context store (it will not be filesystem based), we have not yet considered how this might be applied to the device situation.

Being able to to toggle the editor on for a device is something we can look at in a future release, but at the moment that is not possible as described in the other issue.

Please remember that Device support is in it's first Alpha release.

**Comment by grawsom** [comment]
Maybe I should say that I will not be using cloud, but local or docker - at the moment local on Win11.
Regarding editor 👍 
I'm all aware about the Alpha state, but I'm so excited to see if this can help me in the future, that I'm testing all my stuff with this new feature - keep up the great work :-)

**Comment by hardillb** [comment]
Cloud in this context is the core FlowForge platform where the "parent" project for the devices run

**Comment by hardillb** [comment]
Per device environment variables are in plan, hopefully in the next release

**Comment by grawsom** [comment]
> Per device environment variables are in plan, hopefully in the next release

👍
