### ISSUE TITLE
Docker Device Agent failed to pull snapshot after restart

### ISSUE THREAD

**Issue by robmarcer** [flowforge/flowforge-device-agent#162]
### Current Behavior

After a nightly restart of the Device Agent running on Docker, the process of getting the snapshot timed out.

![Annotation-Annotation on 2023-08-21 at 16-20-14 png](https://github.com/flowforge/flowforge-device-agent/assets/92092324/e79fd33e-c445-4377-90a6-de66aa2726ce)

### Expected Behavior

The Device agent should keep retrying the snapshot download if the prior attempt timed out.

### Steps To Reproduce

The network this device is running on is believed to have restarted at the same time as the device agent.

### Environment

- FlowForge version: FF Cloud 1.10.2
- Node.js version: 16.20.2
- npm version:
- Platform/OS:
- Browser:

**Comment by robmarcer** [comment]
I've done some testing on this issue. I've used a slow network simulator (https://www.sitespeed.io/documentation/throttle/)to test what happens if the device agent can't get the snapshot within the 10000ms limit.

It seems that if it fails to get the snapshot in time the following error is shown:

[AGENT] 8/24/2023 8:24:59 PM [warn] Problem getting snapshot: TimeoutError: Timeout awaiting 'request' for 10000ms

It seems that the device agent then just hangs.

In my testing I created a 3MB snapshot (it contains 3 inject nodes which each have a 1MB string in them) and slowed my network down to 50kb up, 50kb down.

Video shows the test - https://d.pr/v/vGRjJR

**Comment by hardillb** [comment]
OK, but 50kps is very slow by modern network standards.

What timeout should be use? We could double the current 10 second would that be enough?

**Comment by robmarcer** [comment]
Thanks @hardillb, this is a great fix for now. As discussed, I think there is something off with the retry logic for this particular timeout. It seems that once the snapshot download fails once the system doesn't retry, where as various other scenarios I tested seem to periodically repeat the failed action.

**Comment by hardillb** [comment]
How big are their snapshots, and just how slow is their network?

**Comment by robmarcer** [comment]
Snapshots are 280KB (well slighting more as that number is for the flow not the full snapshot), ~20 device agents running on the same machine so ~5.6MB of data to pull.

Anything under a ~1.5Mb connection would result in a timeout.

**Comment by hardillb** [comment]
So they are effectively DoSing themselves by mass restarting them all at the same time.

The "right" solution may be that they stagger the restart....

**Comment by knolleary** [comment]
I think the fact they are restarting them all at the same time is part of the issue, but something we ought to be able to handle.

The proper fix on our side here is to add some retry logic here so if it does timeout (which could happen for all sorts of reasons) then it tries again without blocking progress.

**Comment by robmarcer** [comment]
I think that's the best tactic, agreed. I also would like to understand if it was the intention that the snapshot download would retry. From my limited testing it seems that the agent does retry if the network is totally down but doesn't retry if the network was up but too slow, that seems like either a bug or oversight.

**Comment by hardillb** [comment]
I may have worked out where to insert the fix to get it to retry. If rob can test I can give you a 3 line change to a single file.

**Comment by robmarcer** [comment]
I've suggest a staggering of the restarts. Also suggest the user does the restarts in series. Finally I've asked if they can use a tool to measure the internet speed on the device in question at the restart time.

I can do testing @hardillb, I've still got the setup I used to recreate the issue.

**Comment by MarianRaphael** [comment]
A customer pushed an update (new target snapshot) yesterday and one device in the fleet didn’t take it. DA Version 1.10.1.


![Image](https://github.com/flowforge/flowforge-device-agent/assets/73583313/1846c36b-9a53-4a6e-946f-b7f4089a58b8)



![Image](https://github.com/flowforge/flowforge-device-agent/assets/73583313/96a25792-fabd-4170-ba2e-a303eb7d28aa)
