### ISSUE TITLE
Logs for Agent and Node-RED appear to use different Timezones

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge-device-agent#30]
### Current Behavior

The log output for a device running a Node-RED flow (with project link nodes) shows some strange behaviour, the reason the connection went up and down was because  my ISP was flipping, there are 2 types of entries in the log output, some from the Node-RED application prefixed with [NR] and some from the agent itself.
The times for the agent appear to be in UTC, however the times for the Node-RED application appear to be in localtime (BST)
This is very confusing when the logs are displayed together.
```
NR] 17 Aug 18:05:43 - [info] Project Link nodes connection closed
[NR] 17 Aug 18:05:54 - [info] Project Link nodes connected
[2022-08-17T17:06:18.089Z] INFO: MQTT reconnecting to platform
[2022-08-17T17:29:51.280Z] INFO: MQTT reconnecting to platform
[NR] 17 Aug 18:29:55 - [info] Project Link nodes connection closed
[NR] 17 Aug 18:30:00 - [info] Project Link nodes connected
[NR] 17 Aug 20:26:04 - [info] Project Link nodes connection closed
[NR] 17 Aug 20:26:15 - [info] Project Link nodes connected
[2022-08-17T19:26:25.757Z] INFO: MQTT reconnecting to platform
[NR] 17 Aug 20:39:16 - [info] Project Link nodes connection closed
[NR] 17 Aug 20:39:22 - [info] Project Link nodes connected
[2022-08-17T19:39:28.760Z] INFO: MQTT reconnecting to platform
```

```
pi@sensehatpi:~ $ cat /etc/timezone 
Europe/London
```

### Expected Behavior

All log events should use the same timezone, preferably UTC.

### Steps To Reproduce

Run a device agent on a device with the TZ set to something other than UTC.

Observe timestamps in the log entries

### Environment

- FlowForge version: 0.8.0
- Agent: 0.2.0
- Node.js version: 16.16

**Comment by hardillb** [comment]
This is down to 

https://github.com/flowforge/flowforge-device-agent/blob/2c3552fcd5a0e5c87dc5c728ca111e90c0deb694/lib/log.js#L4

Which is using `toISOString()` which always prints in UTC. The other lines are coming from Node-RED which are in Local time.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
