### ISSUE TITLE
Check for valid version of Node on run

### ISSUE THREAD

**Issue by robmarcer** [flowforge/flowforge-device-agent#37]
### Description

**As a:** user of the device agent

**I want to**: be warned if I am using a version of Node.js which is tool old to run the agent.

**So that:** I don't spend a lot of time stuck trying to work out why the agent will not run. The cause is that Apt is installing 12.* on Debian Bullseye and I think many users will try the Apt install route for Node.js.

### Acceptance Criteria

- [ ] When the agent runs check if installed Node.js version => the minimum supposed version, if not explicitly warn the user that it won't work unless Node.js is updated.

**Comment by hardillb** [comment]
Verified with NodeJS v14 and head of main
