### ISSUE TITLE
Device agent fails to install project nodes on staging

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge-device-agent#40]
### Current Behavior

On an ubuntu guest under WSL (effectively a VM) I am seeing the below ...

```
No matching version found for @flowforge/nr-project-nodes@0.1.2-1bc342e-20221024.0.
```

```
full log...
```
[AGENT] Oct 25, 2022, 2:13:28 PM info: Stopping project
[AGENT] Oct 25, 2022, 2:13:28 PM info: Cleaning project directory
[AGENT] Oct 25, 2022, 2:13:41 PM info: New settings available
[AGENT] Oct 25, 2022, 2:13:41 PM info: Project: 226eb2f5-59d4-4350-807a-1c3bebbdacf8
[AGENT] Oct 25, 2022, 2:13:41 PM info: Snapshot: xVqQX39ga5
[AGENT] Oct 25, 2022, 2:13:41 PM info: Settings: ff59f44eb988d99fa4ef3face3dfb114f5382b3bb809261f373a88d622d1c64e
[AGENT] Oct 25, 2022, 2:13:41 PM info: Updating project configuration files
[AGENT] Oct 25, 2022, 2:13:41 PM info: Installing project dependencies
[AGENT] Oct 25, 2022, 2:13:42 PM warn: Install failed
[AGENT] Oct 25, 2022, 2:13:42 PM warn: npm WARN config production Use `--omit=dev` instead.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @flowforge/nr-project-nodes@0.1.2-1bc342e-20221024.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/steve/.npm/_logs/2022-10-25T13_13_41_483Z-debug-0.log

[AGENT] Oct 25, 2022, 2:13:42 PM warn: Error whilst starting project: Error: Command failed: npm install --production
npm WARN config production Use `--omit=dev` instead.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @flowforge/nr-project-nodes@0.1.2-1bc342e-20221024.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/steve/.npm/_logs/2022-10-25T13_13_41_483Z-debug-0.log

[AGENT] Oct 25, 2022, 2:13:42 PM info: Stopping project
[AGENT] Oct 25, 2022, 2:13:42 PM info: Cleaning project directory
```

### Expected Behavior

Unsure - possibly needs a way to pin version and not use private nightly?

### Steps To Reproduce

add a device on staging
Get YML and start device
assign a project so that device is updated 

### Environment

- FlowForge version: pre 1.0.0 release (git)
- Node.js version: 16
- npm version: 8
- Platform/OS: Linux Ubuntu under WSL2
- Browser: Chrome

**Comment by hardillb** [comment]
Related to version of project-nodes packaged into the container

**Comment by hardillb** [comment]
The fix for this is in the handbook
https://flowforge.com/handbook/development/how-we-work/staging/#using-the-flowforge-device-agent-with-staging
