### ISSUE TITLE
Update package.json contents to contain snapshot information

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge-device-agent#48]
### Description

Via https://github.com/flowforge/flowforge/pull/1506 we added the ability to download a snapshot's package.json directly.

As part of that, we improved the meta data in the file to provide information about the project/snapshot.

We should update the Device Agent to provide similar info when generating its local package.json:

 https://github.com/flowforge/flowforge/pull/1506/files#diff-115c203244da057684886e965e15963292ac1df14072335b3d499b5e1c6822d1R154

**Comment by hardillb** [comment]
Verified on Staging
