### ISSUE TITLE
Add check on node.js version

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge-device-agent#54]
### Description

We should add an explicit node.js version check to the device agent so we can provide a more helpful message if trying to run on an older version of node.js.

This will have to be done right at the start of `index.js` - *before* we require any other modules, as they will hit syntax errors when trying to do the require if node is too old.

Ref: https://github.com/flowforge/flowforge-device-agent/issues/53#issue-1551098547

**Comment by hardillb** [comment]
We already do

https://github.com/flowforge/flowforge-device-agent/blob/b9c64ce7fc2e2db9fb5db687c27f000bbb069682/index.js#L25-L27

**Comment by knolleary** [comment]
But that is too late. If running on node 10 (as per the linked issue), it will fail on line 3 of `index.js` when it tries to require `lib/Agent.js` as that file contains newer syntax.

The check you point to needs moving above any attempt to require any other file.
