### ISSUE TITLE
flowforge-device-agent doesn't start without internet connection

### ISSUE THREAD

**Issue by fdplourde** [flowforge/flowforge-device-agent#61]
### Current Behavior

When I'm connected to the internet, the device agent work has expected when the device boot with the flowforge-device.service is provided in that git. The device agent connect to the internet check if it needed update and install his module and start node-red when all these step are finish.

But when I disconnect from the internet, and reboot the device agent, nothing works anymore. the device agent start on boot but its unable to start node-red, its send me that message in the systemctl :

[AGENT] 28 Mar 2023, 19:34:46 warn: Error whilst starting Node-RED: RequestError: connect ENETUNREACH 206.41.88.50:3009 - Local (0.0.0.>
![image-Mar-28-2023-06-15-50-5703-PM](https://user-images.githubusercontent.com/56861635/228340852-fdf04352-2480-40fe-b8db-cb41cb0b7485.png)
![Image_20230328_113005_083](https://user-images.githubusercontent.com/56861635/228340889-be38314a-7403-4c58-a6a1-b341c26cb8fb.jpg)
![image-Mar-28-2023-06-23-53-5622-PM](https://user-images.githubusercontent.com/56861635/228340934-12c54617-9c41-44ef-a508-09712e0fea4b.png)

### Expected Behavior

I'm expected the device agent to start node-red instead of waiting for an internet connexion.

### Steps To Reproduce

Disconnect the device agent from the internet

### Environment

- FlowForge version:1.3.0
- Node.js version:16.16.0
- npm version: 8.19.2
- Platform/OS: Raspberry Pi OS
- Browser: chrome

**Comment by hardillb** [comment]
This was an intentional choice to prevent devices continuing to run deployed snapshots even after they had been either updated or removed in the FlowForge applications. Having the device check in before starting allows that check to be made.

How ever we can see that this may be something that a user may wish to control and allow existing snapshots to start and run until the device agent can check in with the FlowForge application.

We will look at making this configurable.

**Comment by hardillb** [comment]
> We will look at making this configurable.

Sorry, on reflection it probably won't be configurable, but we can look at flipping the behaviour to starting with what is currently deployed until it can check in

**Comment by fdplourde** [comment]
In our case this is critical, I base a 1 year project on your platform, and before choosing your platform I've did the tests in early 2022 and that was not an issue. Your tech support and your CEO have tell me that is suppose to work like I ask.

The only way I found to bypass that issue is to change the service file to ping google.com and if its not reachable its starting node-red instead with the flowforge directory, But thats not keeping the env variable of the flowforge-device-agent, so its not viable for us.

flowforge-device.service file:

```
[Unit]
Description=FlowForge Device Agent

[Service]
Type=simple
# Run as normal pi user - change to the user name you wish to run FlowForge Device as
User=pi
Group=pi
WorkingDirectory=/opt/flowforge-device

Environment="NODE_OPTIONS=--max_old_space_size=512"

ExecStart=/bin/bash -c "if ping -q -c 1 -W 1 google.com >/dev/null; then /usr/bin/env flowforge-device-agent -p 1881; else /usr/bin/env node-red -p 1880 -s /opt/flowforge-device/project/settings.js -u /opt/flowforge-device/project; fi"

# Use SIGINT to stop
KillSignal=SIGINT
# Auto restart on crash
Restart=on-failure
RestartSec=20
# Tag things in the log
SyslogIdentifier=FlowForgeDevice

[Install]
WantedBy=multi-user.target

```
