### ISSUE TITLE
Node-RED per default – Handle Missing device.yml

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge-device-agent#75]
## Description
As a user, I want the FlowForge Device Agent to start a Node-RED instance with editor access (a default snapshot and a custom module to create a device.yml file) when it detects no device.yml file during startup. This will ensure a smooth user experience and enable users to quickly onboard their devices.

## Background
Currently, the FlowForge Device Agent requires a device.yml file to run a Node-RED instance. As a result, it is challenging to preinstall the device agent on 3rd party devices because shell access for device.yml creation and configuration is necessary.

## Goals

1. Detect the absence of a device.yml file during the startup of the FlowForge Device Agent.
2. Start a Node-RED instance with a default snapshot (empty node-red with ff theme and flowforge-nr-tools-plugin) when no device.yml file is detected.
3. Implement a custom Node-RED module that allows the user to generate a device.yml file via the Node-RED settings section.
4. Continuously monitor if a device.yml file has been created.

**Comment by hardillb** [comment]
We need to talk about this, because the only way to access the editor for the device NR instance is going to be via the FlowForge Web app which needs the device agent to already be connected.

Staring an editor open to be just connected to is not a default safe situation. I do not like this concept.

**Comment by MarianRaphael** [comment]
I fully understand your concerns about the security implications of having an editor open for connection by default. I would like to schedule a short meeting to discuss this in more detail.

My initial thoughts on addressing the security concerns are as follows: We could ensure that the behavior of FlowForge <-> Device Agent remains untouched in this process. During the first initial startup, a Node-RED instance will start, and the user would be able to connect to a Node-RED instance with vanilla settings.js (including custom modules). The user would have the opportunity to modify the settings.js file according to their preferences.

Once a device.yml file is detected, the system would revert to its current implementation, with no direct editor access permitted. This approach would maintain the security of the system while providing users with flexibility. Only during the initial startup would an unsecured Node-RED instance be accessible, similar to what users would experience if they installed Node-RED themselves.

**Comment by MarianRaphael** [comment]
I understand your concerns and agree that having a simple web app for uploading the device.yml file is a more straightforward approach. Tried exactly this within the ctrlX project and onboarding. 

The main challenge for users with third-party devices is that they often have access only to the marketplaces provided by their device manufacturers. This means that we would need to create offerings for both Node-RED and the Device-Agent (for every marketplace) or just for the Device-Agent. By doing so, we might inadvertently give our competitors room to create their own Node-RED offerings in these marketplaces, which could be placed next to our device agent. This is especially concerning since some of these potential competitors are also the marketplace vendors. (see Siemens, Bosch Rexroth etc.)

Anyway, I will create another epic about the web app approach.

**Comment by MarianRaphael** [comment]
### Meeting notes
**Approach to solve the requirement**
Instead of starting NR per default, we will extend flowforge/flowforge-nr-tools-plugin to allow for device.yml creation and switch over to the Device Agent.
https://github.com/flowforge/flowforge-nr-tools-plugin/issues/14
