### ISSUE TITLE
Update statement on Windows support

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge-device-agent#78]
### Description

Windows is currently listed as unsupported. That was based on the original development effort to create the agent.

Given all of the work done by @Steve-Mcl since, we may be in a position to remove that statement with minimal effort.
```[tasklist]
### Tasks
- [ ] Update FlowForge docs: https://github.com/flowforge/flowforge/pull/2320
- [ ] Update Device Agent Readme: #119 
```

**Comment by Steve-Mcl** [comment]
I would say yes. I have ran the agent extensively on windows and in wsl.

**Comment by MarianRaphael** [comment]
Before we officially support Windows, we should provide a "Getting Started" guide. This guide should offer a precise description of the setup process and outline typical issues that might arise (refer to the support request).

My feeling is that customers are already using our product on Windows (even if it is not supported). Therefore, providing documentation will help ensure a smoother user experience and minimize the need for support.

**Comment by iskerrett** [comment]
Is Windows support for just the device agent and the FlowForge platform?

**Comment by Steve-Mcl** [comment]
@iskerrett 

> Is Windows support for just the device agent and the FlowForge platform?

Not certain I fully understand the question?


<br>

Maybe this helps:

The device agent was documented as supporting Linux/MacOs with a statement about _not being tested on windows_.  This update removed that statement.

FlowForge has always been supported on windows (where applicable) and the installation docs for FF state as much.
