### ISSUE TITLE
Allow devices to access details of the snapshot running on them

### ISSUE THREAD

**Issue by robmarcer** [flowforge/flowforge-device-agent#94]
### Description

When working with large sets of devices, it's fair to assume that during a migration to a new snapshot that some devices will continue to run the old snapshot for longer than others.

Where the devices are collecting data from sensors and passing it to a central time series database it would be useful if the data could be tagged as originating from a given snapshot. 

That would allow HMIs both on the shop-floor and in offices to understand which data was generated by a specific snapshot and where needed highlight data from an old build.

**Comment by Steve-Mcl** [comment]
Verified staging -> device

![Image](https://github.com/flowforge/flowforge-device-agent/assets/44235289/ac7bd3f9-2c21-412d-aa25-5c34f87f8d92)
